_depricated/blog/legacy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# ***
class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)

    country = models.CharField(null=True, max_length=120)
    city = models.CharField(null=True, max_length=120)
    birth_date = models.DateField(null=True)
    about = models.TextField(default='')

    rate = models.IntegerField(default=0)
    blog_title = models.CharField(null=True, max_length=120)
    blog_description = models.CharField(null=True, max_length=500)

    avatar = models.CharField(null=True, default=None, max_length=64)

    new_messages_notify = models.BooleanField(default=False)
    new_bookmarked_comments_notify = models.BooleanField(default=False)
    new_my_post_comments_notify = models.BooleanField(default=False)

    always_keep_bookmarks = models.BooleanField(default=False)
    keep_bookmarks = models.IntegerField(default=3)

    filter_all = 1
    filter_include = 2
    filter_exclude = 3

    filter_users = models.IntegerField(default=filter_all)
    filter_tags = models.IntegerField(default=filter_all)

# ***
class Tag(models.Model):
    name = models.CharField(max_length=120, default='') #TODO dummy
    title = models.CharField(max_length=120)
    description = models.CharField(max_length=500, default='') #TODO dummy
    parent = models.ForeignKey('self', null=True) #TODO dummy
    post_count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

# ***
class UserTag(models.Model):
    title = models.CharField(max_length=120)
    post_count = models.IntegerField(default=0)
    user = models.ForeignKey(User)

# ***
class FilterUser(models.Model):
    stream_owner = models.ForeignKey(User, related_name='stream_owner')
    filtered_user = models.ForeignKey(User, related_name='filtered_user')

# ***
class FilterTag(models.Model):
    stream_owner = models.ForeignKey(User)
    filtered_tag = models.ForeignKey(Tag)

# ***
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=120)
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    rubric = models.CharField(max_length=16, default='') #TODO dummy
    author = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag, null=True)

    def __unicode__(self):
        return self.title


# ***
class Bookmark(models.Model):
    hit_time = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)
    hit_comment_count = models.IntegerField()
    pinned = models.BooleanField(default=False)

    def __unicode__(self):
        return self.post.title


# ***
class PostHit(models.Model):
    hit_time = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)
    hit_comment_count = models.IntegerField()


# ***
class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(default=0)
    author = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    parent = models.ForeignKey('self', null=True)
    level = models.IntegerField(default=0)

    def __unicode__(self):
        return self.text

# ***
class Vote(models.Model):
    voting_user = models.ForeignKey(User, related_name='voting_users') # This is author of the vote
    target_user = models.ForeignKey(User, related_name='target_users') # This is target of the vote
    post = models.ForeignKey(Post, null=True)
    comment = models.ForeignKey(Comment, null=True)
    value = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)
    up = 1
    down = -1


class PrivateMessage(models.Model):
    status_normal = 0
    status_trash = 1
    status_deleted = 2
    from_user = models.ForeignKey(User, related_name='from_users')
    to_user = models.ForeignKey(User, related_name='to_users')
    send_time = models.DateTimeField(auto_now_add=True)
    read_time = models.DateTimeField(null=True)
    subject = models.CharField(max_length=120)
    text = models.TextField()
    sender_status = models.IntegerField(default=status_normal)
    receiver_status = models.IntegerField(default=status_normal)

# ***
class Poll(models.Model):
    post = models.ForeignKey(Post)
    limit = models.IntegerField()
    deadline = models.DateTimeField()

# ***
class PollVariant(models.Model):
    poll = models.ForeignKey(Poll)
    text = models.CharField(max_length=500)
    hits = models.IntegerField(default=0)

# ***
class PollVote(models.Model):
    poll = models.ForeignKey(Poll)
    variant = models.ForeignKey(PollVariant, null=True, default=None)
    user = models.ForeignKey(User)


def create_profile(sender, **kw):
    user = kw["instance"]
    if kw["created"]:
        profile = UserProfile(user=user, rate=0)
        profile.save()

post_save.connect(create_profile, sender=User, dispatch_uid="users-profilecreation-signal")

# HQ
class Roster(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(default='', max_length=120)
    guid = models.CharField(max_length=36)
    limit = models.IntegerField(null=True)
    system = models.CharField(max_length=8)
    army = models.CharField(max_length=8)

class Unit(models.Model):
    roster = models.ForeignKey(Roster)
    guid = models.CharField(max_length=36)
    name = models.CharField(default='', max_length=120)
    type = models.CharField(max_length=16)
    section = models.CharField(max_length=16)

class Option(models.Model):
    unit = models.ForeignKey(Unit)
    name = models.CharField(max_length=16)
    value = models.CharField(max_length=16)

_depricated/blog/__init__.py
__author__ = 'dante'

from _depricated.blog.views import module

_depricated/blog/legacy/__init__.py
__author__ = 'dante'

_depricated/blog/legacy/controllers/__init__.py
__author__ = 'dante'

_depricated/blog/legacy/controllers/comment.py
__author__ = 'dante'

from django.core.mail import EmailMessage
from waaagh.multiblog.models import Comment, PostHit, Bookmark
from waaagh.multiblog.tools.mail import send_email
from waaagh.multiblog.tools.text import auto_mark_links, normalize_line_breaks
from waaagh.multiblog.messages import new_comment_msg, new_comment_subj

def edit_comment(comment, text, proc_ref=True, proc_images=True, proc_lines=True):
    comment.text = get_comment_text(text, proc_ref, proc_images, proc_lines)
    comment.save()

def new_comment(author, post, parent, text, proc_ref=True, proc_images=True, proc_lines=True):
    comment = Comment(
        text=get_comment_text(text, proc_ref, proc_images, proc_lines),
        author=author,
        post=post)
    if parent is not None:
        comment.parent = parent
        comment.level = parent.level + 1
    comment.save()
    post.comments = Comment.objects.filter(post=post).count()
    post.save()

    try:
        hit = PostHit.objects.get(post=post, user=author)
        hit.hit_comment_count += 1
        hit.save()
    except Exception:
        pass

    try:
        bm = Bookmark.objects.get(post=post, user=author)
        bm.hit_comment_count += 1
    except Exception:
        bm = Bookmark(post=post, user=author, hit_comment_count=post.comments)
    bm.save()

    to = []
    for notify in Bookmark.objects.filter(post=post):
        if notify.user.get_profile().new_bookmarked_comments_notify and notify.user.username != author.username:
            to.append(notify.user.email)
    if len(to) is not 0:
        send_email(EmailMessage(new_comment_subj,
            new_comment_msg % {'author':author.username,
                               'text': text,
                               'title': post.title,
                               'post_id': post.id}, bcc=to))

    return comment

def get_comment_text(text, process_ref, process_images, process_lines):
    if process_ref or process_images:
        text = auto_mark_links(text, process_ref, process_images)
    if process_lines:
        text = normalize_line_breaks(text)
    return text

_depricated/blog/legacy/controllers/online.py
__author__ = 'dromanov'

from datetime import datetime, timedelta

online_users = {}

def add_online_user(user):
    online_users[user] = datetime.now()

def get_online_users():
    for u in list(online_users.keys()):
        if online_users[u] < datetime.now() - timedelta(minutes=5):
            online_users.pop(u)
    return list(online_users.keys())

if __name__ == '__main__':
    import time
    add_online_user('Dante')
    print(get_online_users())

    time.sleep(2)
    add_online_user('Waaagh')
    print(get_online_users())

    time.sleep(2)
    print(get_online_users())

    time.sleep(2)
    print(get_online_users())

_depricated/blog/legacy/controllers/stable.py
__author__ = 'dante'

from waaagh.multiblog.models import Post, Tag, PrivateMessage, User, UserTag
from waaagh.multiblog.consts import most_commented_limit, most_rated_limit
from waaagh.multiblog.controllers.online import get_online_users, add_online_user
from waaagh.multiblog.controllers.post_list import get_bookmarked_posts_headers

# Stable data structure:
#   stable
#       current_tag
#       auth: #TODO
#       current_post
#           id
#           can_edit
#       current_user
#           username
#           my_user True if current user is auth user
#       current_blog
#           author
#           title
#           description
#           my_blog: True if it's auth blog
#       blog_ref: "/blog/<current_blog.author>" or ""
#       side_bar
#           bookmarks
#           most_rated
#           most_commented
#           tags
#           online

def get_side_tags(user):
    if user is None:
        return Tag.objects.exclude(post_count=0).order_by('-post_count')
    else:
        return UserTag.objects.filter(user = user).exclude(post_count=0).order_by('-post_count')

def side_bar_data(request, current_blog_author):
    data = {
        'most_rated': Post.objects.order_by('-rate')[0:most_rated_limit],
        'most_commented': Post.objects.order_by('-comments')[0:most_commented_limit],
        'tags': get_side_tags(current_blog_author),
        'online': get_online_users(),
    }
    if request.user.is_authenticated():
        data['bookmarks'] = get_bookmarked_posts_headers(request.user)
    return data

def get_auth_info(request):
    if not request.user.is_authenticated():
        return None
    add_online_user(request.user.username)
    return {
        'username': request.user.username,
        'unread_mail': PrivateMessage.objects.filter(to_user=request.user, read_time=None).count(),
        'avatar': request.user.get_profile().avatar,
        }

def get_current_blog(request, author):
    if not author:
        return None
    return {
        'author': author.username,
        'title': author.get_profile().blog_title,
        'description': author.get_profile().blog_description,
        'my_blog': request.user.username == author.username if request.user.is_authenticated() else False,
    }

def get_blog_ref_prefix(author):
    if not author:
        return ''
    return '/blog/' + author.username

def get_current_user(request, user):
    if not user:
        return None
    return {
        'username': user.username,
        'my_user': user.username == request.user.username if request.user.is_authenticated() else False,
    }

def get_stable_data(request, tag = None, current_user = None, current_blog_author = None):
    current_user = User.objects.get(username=current_user) if current_user else None
    current_blog_author = User.objects.get(username=current_blog_author) if current_blog_author else None
    return {
        'auth': get_auth_info(request),
        'side_bar': side_bar_data(request, current_blog_author),
        'current_tag': tag,
        'current_user': get_current_user(request, current_user),
        'current_blog': get_current_blog(request, current_blog_author),
        'blog_ref': get_blog_ref_prefix(current_blog_author),
    }

_depricated/blog/legacy/controllers/tags.py
# -*- coding: utf-8 -*-

__author__ = 'dante'
from waaagh.multiblog.models import Post, Tag, UserTag

def get_tags_list():
    return Tag.objects.exclude(post_count=0).order_by('-post_count')

#TODO: temporary conversion code
def fix_tags():
    rubrics = [
        {'ref': 'news', 'title': 'Новости', 'post_to': 'Новости'},
        {'ref': 'articles', 'title': 'Статьи', 'post_to': 'Статьи'},
        {'ref': 'qa', 'title': 'Вопросы', 'post_to': 'Вопросы'},
        {'ref': 'flame', 'title': 'Дискуссии', 'post_to': 'Дискуссии'},
        {'ref': 'offtopic', 'title': 'Offtopic', 'post_to': 'Offtopic'},
        {'ref': 'fight', 'title': 'Дуэли', 'post_to': 'Дуэли'},
        ]
    for rubric in rubrics:
        tag = Tag(name=rubric['ref'], title=rubric['title'])
        tag.save()
        rubric['tag'] = tag
        print("tag %s added" % tag.name)
    for post in Post.objects.all():
        for rubric in rubrics:
            if post.rubric == rubric['ref']:
                post.tags.add(rubric['tag'])
                post.save()
                rubric['tag'].post_count += 1
                print("post %d tag %s added" % (post.id, rubric['tag'].name))
    for rubric in rubrics:
        rubric['tag'].save()


def fix_user_tags():
    for post in Post.objects.all():
        for tag in post.tags.all():
            try:
                user_tag = UserTag.objects.get(title = tag.title, user = post.author)
                user_tag.post_count = Post.objects.filter(tags__id = tag.id, author = post.author).count()
            except UserTag.DoesNotExist:
                user_tag = UserTag(title = tag.title, user = post.author, post_count = 1)
            user_tag.save()
            print("post %d tag %s added" % (post.id, tag.title))
#    # Update changed tags post counts
#    for tag in fix_tags.keys():
#        if fix_tags[tag] is not None:
#            fix_tags[tag].post_count = Post.objects.filter(tags__id = fix_tags[tag].id).count()
#            fix_tags[tag].save()
#            try:
#                user_tag = UserTag.objects.get(title = fix_tags[tag].title, user = post.author)
#                user_tag.post_count = Post.objects.filter(tags__id = fix_tags[tag].id, author = post.author).count()
#            except UserTag.DoesNotExist:
#                user_tag = UserTag(title = fix_tags[tag].title, user = post.author, post_count = 1)
#            user_tag.save()

_depricated/blog/legacy/tools/__init__.py
__author__ = 'dante'

_depricated/blog/views.py
from _depricated.blog import post_list

__author__ = 'dante'

from flask import Blueprint, render_template, jsonify, request, url_for
from flask.ext.login import current_user
import json

module = Blueprint('blog', __name__)


@module.route('/post/<post_id>')
def post(post_id):
    return render_template("../templates/blog/post.html", data=post_utils.get_single_post(post_id))


@module.route('/_update_post', methods=['POST'])
def update_post():
    if not current_user.is_authenticated():
        return jsonify(redirect=url_for('auth.signin_page'))
    return jsonify(result=post_utils.update_post(json.loads(request.form.get('data'))))

#
# @module.route('/_post_list_data', methods=['POST'])
# def post_list_data():
#     data = json.loads(request.form.get('data'))
#
#     def safe_get(key):
#         return data[key] if key in data.keys() else None
#
#     return jsonify(result=posts_list_data(safe_get('page'), safe_get('tag'), safe_get('user')))

@module.route('/')
@module.route('/<int:page>')
@module.route('/blog/<string:author>')
@module.route('/blog/<string:author>/<int:page>')
@module.route('/blog/<string:author>/tag/<string:tag>')
@module.route('/blog/<string:author>/tag/<string:tag>/<int:page>')
@module.route('/tag/<string:tag>')
@module.route('/tag/<string:tag>/<int:page>')
def main(page=0, author=None, tag=None):
    return render_template("blog/main.html", data=post_list(page=page, author=author, tag=tag))

_depricated/blog2/blog/__init__.py
__author__ = 'dromanow'

from .views import module

_depricated/blog2/blog/views.py
from .blog.tools import process_post, get_data, get_posts

__author__ = 'Denis Romanov'

from flask import Blueprint, render_template, jsonify, request, url_for
from flask.ext.login import current_user
import json

module = Blueprint('blog', __name__, url_prefix='/social')


@module.route('/_update_post', methods=['POST'])
def update_post():
    data = json.loads(request.form.get('data'))
    res = get_data(data)
    if res:
        return jsonify(res)
    if not current_user.is_authenticated():
        return jsonify(redirect=url_for('auth.signin_page'))
    return jsonify(process_post(data, current_user))


@module.route('/')
@module.route('/user/<user>')
@module.route('/tag/<tag>')
@module.route('/post/<post>')
def main(user=None, tag=None, post=None):
    return render_template(
        "blog/main.html",
        posts=get_posts(user=user, tag=tag, post=post),
        post=post, tag=tag, user=user
    )

_depricated/templates/blog/legacy/comment_text.html
{% load markup %}
<div>{{ comment.text|markdown }}</div>

_depricated/templates/blog/legacy/login.html
{% extends "main.html" %}

{% block text_area %}
    <div class="row-fluid">

        {% load widget_tweaks %}
        <div class="span7">
            {% block data_form %}
            <div class="row-fluid">
            <form class="form-horizontal" action="" method="POST">
                <fieldset>
                    <div class="control-group {% if form.name.errors %}error{% endif %}">
                        <label class="control-label" for="id_name">Имя</label>
                        <div class="controls">
                            {{ form.name|add_class:"span12" }}
                            {% for error in form.name.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="control-group {% if form.password.errors %}error{% endif %}">
                        <label class="control-label" for="id_password">Пароль</label>
                        <div class="controls">
                            {{ form.password|add_class:"span12" }}
                            {% for error in form.password.errors %}
                            <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-actions">
                        <a class="btn" href="/amnesia">Забыли пароль</a>
                        <button class="btn btn-primary" type="submit">Войти</button>
                    </div>
                </fieldset>
            </form>
            </div>
            {% endblock %}
        </div>
        <div class="span5">
            {% block help_text %}
            <p>Добро пожаловать!</p>
            <p>Что бы воспользоваться всеми функциями сайта Вам необходимо <a href="/new_user">зарегистрироваться</a> и <a href="/login">войти</a>.</p>
            <p>После этого Вы можете не только читать содержимое, но и публиковать собственные <a href="/rubric/articles">статьи</a>, задавать <a href="/rubric/qa">вопросы</a>, участвовать в <a href="/rubric/flame">обсуждениях</a>, писать в свой <a href="/rubric/blogs">личный блог</a>, а также же получите возможность воспользоваться многими новыми классными функциями которые обязательно будут добавлены в будущем.</p>
            <p>Что бы Ваше общение было комфортным и приятным возможно стоит ознакомиться с дополнительной <a href="/about">информацией о ресурсе</a>, <a href="/rules">правилами сообщества</a>, и небольшой <a href="/help">помощью</a> по функциям. Если у Вас возникнут сложности, <a href="/admins">администраторы</a> ресурса обязательно постараются Вам помочь.</p>
            <p>Надеемся Вам здесь понравиться.</p>
            {% endblock %}
        </div>
    </div>
{% endblock %}

_depricated/templates/blog/legacy/mail_text.html
{% load markup %}
<div>
        <h2>{{ mail.zone.message.subject }}</h2>
</div>
<div>
        <p>{{ mail.zone.message.text|markdown }}</p>
</div>

_depricated/templates/blog/legacy/new_comment.html
{% extends "main.html" %}

{% block scripts %}
    <script type="text/javascript" xmlns="http://www.w3.org/1999/html" src="/static/extern/markitup/jquery.markitup.js"></script>
    <script type="text/javascript" src="/static/extern/markitup/sets/markdown/set_comment.js"></script>
    <script type="text/javascript">
        function preview_comment_callback(preview) {
            var alert = "<div class=\"alert alert-error\"> \
                 <button class=\"close\" data-dismiss=\"alert\">×</button> \
                 <strong>Внимание!</strong> Это только предварительный просмотр, на забудте отправить пост если Вас все устраивает. \
            </div> "
            $("#preview_area").html(alert + preview.preview_text + '<hr>');
        }
        $(document).ready(function () {
            $("textarea").markItUp(mySettings);
            $("#preview").click(function () {
                Dajaxice.waaagh.multiblog.preview_comment(preview_comment_callback, {
                    'text':$('#id_text').val(),
                    'proc_ref': $('#id_proc_ref').is(':checked'),
                    'proc_images': $('#id_proc_images').is(':checked'),
                    'proc_lines': $('#id_proc_lines').is(':checked')
                });
            })
        });
    </script>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="/static/extern/markitup/skins/simple/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/extern/markitup/sets/markdown/style_comment.css"/>
{% endblock %}

{% block text_area %}
<div class="row-fluid">
    <div id='preview_area'>&nbsp;</div>
    <form class="form-horizontal" action="" method="POST">
        <fieldset>
        <div class="control-group">
            <label class="control-label" for="id_text">Текст</label>
            <div class="controls">
                <textarea class="span12" id="id_text" name="text">{{ form.text }}</textarea>
            </div>
        </div>
        {% include "text_autoformat.html" %}
        <div class="form-actions">
            <input id="preview" class="btn" type="button" value="Предпросмотр">
            <button class="btn btn-primary" type="submit">Отправить</button>
        </div>
        </fieldset>
    </form>
</div>
{% endblock %}

_depricated/templates/blog/legacy/new_post.html
{% extends "main.html" %}

{% block scripts %}
    <script type="text/javascript" xmlns="http://www.w3.org/1999/html" src="/static/extern/markitup/jquery.markitup.js"></script>
    <script type="text/javascript" src="/static/extern/markitup/sets/markdown/set.js"></script>
    {% load compress %}
    {% compress js %}
    <script type="text/javascript" src="/static/scripts/tools.js"></script>
    <script type="text/javascript" src="/static/scripts/edit_post.js"></script>
    {% endcompress %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("textarea").markItUp(mySettings);
        });
    </script>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="/static/extern/markitup/skins/simple/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/extern/markitup/sets/markdown/style.css"/>
{% endblock %}

{% block text_area %}
<div class="row-fluid" id="new_post" >
    <div id="alert_area">
        <div data-bind="visible: connectionError">
            <div class="alert alert-error">
                <strong>Ошибка!</strong> Не удалось подключиться к серверу, проверьте соединение с интернетом и повторите попытку.
            </div>
        </div>
        <div data-bind="visible: emptyText">
            <div class="alert alert-error">
                <strong>Ошибка!</strong> Текст сообщения не может быть пустым.
            </div>
        </div>
        <div data-bind="visible: emptyTitle">
            <div class="alert alert-error">
                <strong>Ошибка!</strong> Заголовок сообщения не может быть пустым.
            </div>
        </div>
        <div data-bind="visible: showPreview">
            <div class="alert alert-warning">
                <button class="close" data-bind="click: previewClose">×</button>
                <strong>Внимание!</strong> Это только предварительный просмотр, на забудте отправить пост если Вас все устраивает.
            </div>
            <div data-bind="html: previewBlock"></div>
            <hr>
        </div>
    </div>
    <form class="form-horizontal" action="" method="POST">
        <fieldset>
        <div class="control-group">
            <label class="control-label">Заголовок</label>
            <div class="controls">
                <input class="span12" id="id_title" type="text" name="title" maxlength="120" data-bind="value: title" value="{{ form.title }}"/>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Текст</label>
            <div class="controls">
                <textarea class="span12" id="id_text" name="text" data-bind="value: text">{{ form.text }}</textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Разделы</label>
            <div class="controls">
                <input class="span12" id="id_tags" type="text" maxlength="300" data-bind="value: tagsString"/>
            </div>
            <div class="controls">
                <div data-bind="foreach: tags">
                <label class="checkbox inline" style="margin-left: 0px; margin-right: 10px">
                <input type="checkbox" data-bind="checked: $data.value"><span data-bind="text: $data.title"></span>
                </label>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Форматирование</label>
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" data-bind="checked: procRef">Автоматическое распознавание ссылок
                </label>
                <label class="checkbox">
                    <input type="checkbox" data-bind="checked: procImages">Автоматическая вставка изображений
                </label>
                <label class="checkbox">
                    <input type="checkbox" data-bind="checked: procLines">Автоматическое форматирование абзацев
                </label>
            </div>
        </div>
            <div class="control-group" data-bind="visible: poll">
                <label class="control-label">Голосование</label>
                <div class="controls">
                    <div class="input-append" >
                        <input data-bind="value: variant" type="text">
                        <button class="btn" data-bind="click: addVariant"><i class="icon-plus"></i></button>
                    </div>
                    <span class="help-inline">Добавить вариант для голосования</span>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div data-bind="foreach: variants">
                        <div class="alert alert-info" style="overflow: auto;">
                            <a class="close" data-bind="click: $parent.removeVariant" href="#">×</a>
                            <span data-bind="text: $data"></span>
                        </div>
                    </div>
                    <div data-bind="visible: pollingLimitVisible">
                        <p>
                            <select class="input-mini" data-bind="options: variantNumbers, value: variantCount"></select>
                            <span class="help-inline">Максимальное количество вариантов</span>
                        </p>
                        <p>
                            <select class="input-mini" data-bind="options: pollTimeNumbers, value: pollTime"></select>
                            <span class="help-inline">Максимальный срок голосования (дней)</span>
                        </p>
                    </div>
                </div>
            </div>
        <div class="form-actions">
            <input id="preview" class="btn" type="button" value="Предпросмотр" data-bind="click: preview">
            <input class="btn btn-primary" type="button" value="Отправить" data-bind="click: send">
        </div>
        </fieldset>
    </form>
    <script type="text/javascript">
        ko.applyBindings(new NewPost({% if form.edit %}{{ form.id }}{% else %}undefined{% endif %}, $('#id_title').val(), $('#id_text').val(), [ {% for tag in form.tags %}
                { value: {% if tag.selected %}true{% else %}false{% endif %}, title: "{{ tag.data.title|safe }}" },{% endfor %}
        ] ), document.getElementById("new_post"));
    </script>
</div>
{% endblock %}

_depricated/templates/blog/legacy/post_poll.html
<div>
    <ul>
    {% for variant in post.poll %}
        <li><p>{{ variant.text }}</p>
        <div class="progress">
            <div class="bar" style="width: {{ variant.percent|floatformat:-0 }}%;">{{ variant.percent|floatformat }}% [{{ variant.num }}]</div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>

_depricated/templates/blog/legacy/search.html
{% extends "main.html" %}

{% block text_area %}
    <div>
        <div id="cse" style="width: 100%;">Loading</div>
        <script src="http://www.google.com/jsapi" type="text/javascript"></script>
        <script type="text/javascript">
            google.load('search', '1', {language : 'ru', style : google.loader.themes.V2_DEFAULT});
            google.setOnLoadCallback(function() {
                var customSearchOptions = {};  var customSearchControl = new google.search.CustomSearchControl(
                        '009349168568658283888:dxm3irw7e4w', customSearchOptions);
                customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
                var options = new google.search.DrawOptions();
                options.enableSearchResultsOnly();
                customSearchControl.draw('cse', options);
                function parseParamsFromUrl() {
                    var params = {};
                    var parts = window.location.search.substr(1).split('\x26');
                    for (var i = 0; i < parts.length; i++) {
                        var keyValuePair = parts[i].split('=');
                        var key = decodeURIComponent(keyValuePair[0]);
                        params[key] = keyValuePair[1] ?
                                decodeURIComponent(keyValuePair[1].replace(/\+/g, ' ')) :
                                keyValuePair[1];
                    }
                    return params;
                }

                var urlParams = parseParamsFromUrl();
                var queryParamName = "q";
                if (urlParams[queryParamName]) {
                    customSearchControl.execute(urlParams[queryParamName]);
                }
            }, true);
        </script>
    </div>
{% endblock %}