_depricated/blog/__init__.py
__author__ = 'dante'

from _depricated.blog.views import module

_depricated/blog/legacy/__init__.py
__author__ = 'dante'

_depricated/blog/legacy/controllers/__init__.py
__author__ = 'dante'

_depricated/blog/legacy/controllers/comment.py
__author__ = 'dante'

from django.core.mail import EmailMessage
from waaagh.multiblog.models import Comment, PostHit, Bookmark
from waaagh.multiblog.tools.mail import send_email
from waaagh.multiblog.tools.text import auto_mark_links, normalize_line_breaks
from waaagh.multiblog.messages import new_comment_msg, new_comment_subj

def edit_comment(comment, text, proc_ref=True, proc_images=True, proc_lines=True):
    comment.text = get_comment_text(text, proc_ref, proc_images, proc_lines)
    comment.save()

def new_comment(author, post, parent, text, proc_ref=True, proc_images=True, proc_lines=True):
    comment = Comment(
        text=get_comment_text(text, proc_ref, proc_images, proc_lines),
        author=author,
        post=post)
    if parent is not None:
        comment.parent = parent
        comment.level = parent.level + 1
    comment.save()
    post.comments = Comment.objects.filter(post=post).count()
    post.save()

    try:
        hit = PostHit.objects.get(post=post, user=author)
        hit.hit_comment_count += 1
        hit.save()
    except Exception:
        pass

    try:
        bm = Bookmark.objects.get(post=post, user=author)
        bm.hit_comment_count += 1
    except Exception:
        bm = Bookmark(post=post, user=author, hit_comment_count=post.comments)
    bm.save()

    to = []
    for notify in Bookmark.objects.filter(post=post):
        if notify.user.get_profile().new_bookmarked_comments_notify and notify.user.username != author.username:
            to.append(notify.user.email)
    if len(to) is not 0:
        send_email(EmailMessage(new_comment_subj,
            new_comment_msg % {'author':author.username,
                               'text': text,
                               'title': post.title,
                               'post_id': post.id}, bcc=to))

    return comment

def get_comment_text(text, process_ref, process_images, process_lines):
    if process_ref or process_images:
        text = auto_mark_links(text, process_ref, process_images)
    if process_lines:
        text = normalize_line_breaks(text)
    return text

_depricated/blog/legacy/controllers/online.py
__author__ = 'dromanov'

from datetime import datetime, timedelta

online_users = {}

def add_online_user(user):
    online_users[user] = datetime.now()

def get_online_users():
    for u in list(online_users.keys()):
        if online_users[u] < datetime.now() - timedelta(minutes=5):
            online_users.pop(u)
    return list(online_users.keys())

if __name__ == '__main__':
    import time
    add_online_user('Dante')
    print(get_online_users())

    time.sleep(2)
    add_online_user('Waaagh')
    print(get_online_users())

    time.sleep(2)
    print(get_online_users())

    time.sleep(2)
    print(get_online_users())

_depricated/blog/legacy/controllers/stable.py
__author__ = 'dante'

from waaagh.multiblog.models import Post, Tag, PrivateMessage, User, UserTag
from waaagh.multiblog.consts import most_commented_limit, most_rated_limit
from waaagh.multiblog.controllers.online import get_online_users, add_online_user
from waaagh.multiblog.controllers.post_list import get_bookmarked_posts_headers

# Stable data structure:
#   stable
#       current_tag
#       auth: #TODO
#       current_post
#           id
#           can_edit
#       current_user
#           username
#           my_user True if current user is auth user
#       current_blog
#           author
#           title
#           description
#           my_blog: True if it's auth blog
#       blog_ref: "/blog/<current_blog.author>" or ""
#       side_bar
#           bookmarks
#           most_rated
#           most_commented
#           tags
#           online

def get_side_tags(user):
    if user is None:
        return Tag.objects.exclude(post_count=0).order_by('-post_count')
    else:
        return UserTag.objects.filter(user = user).exclude(post_count=0).order_by('-post_count')

def side_bar_data(request, current_blog_author):
    data = {
        'most_rated': Post.objects.order_by('-rate')[0:most_rated_limit],
        'most_commented': Post.objects.order_by('-comments')[0:most_commented_limit],
        'tags': get_side_tags(current_blog_author),
        'online': get_online_users(),
    }
    if request.user.is_authenticated():
        data['bookmarks'] = get_bookmarked_posts_headers(request.user)
    return data

def get_auth_info(request):
    if not request.user.is_authenticated():
        return None
    add_online_user(request.user.username)
    return {
        'username': request.user.username,
        'unread_mail': PrivateMessage.objects.filter(to_user=request.user, read_time=None).count(),
        'avatar': request.user.get_profile().avatar,
        }

def get_current_blog(request, author):
    if not author:
        return None
    return {
        'author': author.username,
        'title': author.get_profile().blog_title,
        'description': author.get_profile().blog_description,
        'my_blog': request.user.username == author.username if request.user.is_authenticated() else False,
    }

def get_blog_ref_prefix(author):
    if not author:
        return ''
    return '/blog/' + author.username

def get_current_user(request, user):
    if not user:
        return None
    return {
        'username': user.username,
        'my_user': user.username == request.user.username if request.user.is_authenticated() else False,
    }

def get_stable_data(request, tag = None, current_user = None, current_blog_author = None):
    current_user = User.objects.get(username=current_user) if current_user else None
    current_blog_author = User.objects.get(username=current_blog_author) if current_blog_author else None
    return {
        'auth': get_auth_info(request),
        'side_bar': side_bar_data(request, current_blog_author),
        'current_tag': tag,
        'current_user': get_current_user(request, current_user),
        'current_blog': get_current_blog(request, current_blog_author),
        'blog_ref': get_blog_ref_prefix(current_blog_author),
    }

_depricated/blog/legacy/controllers/tags.py
# -*- coding: utf-8 -*-

__author__ = 'dante'
from waaagh.multiblog.models import Post, Tag, UserTag

def get_tags_list():
    return Tag.objects.exclude(post_count=0).order_by('-post_count')

#TODO: temporary conversion code
def fix_tags():
    rubrics = [
        {'ref': 'news', 'title': 'Новости', 'post_to': 'Новости'},
        {'ref': 'articles', 'title': 'Статьи', 'post_to': 'Статьи'},
        {'ref': 'qa', 'title': 'Вопросы', 'post_to': 'Вопросы'},
        {'ref': 'flame', 'title': 'Дискуссии', 'post_to': 'Дискуссии'},
        {'ref': 'offtopic', 'title': 'Offtopic', 'post_to': 'Offtopic'},
        {'ref': 'fight', 'title': 'Дуэли', 'post_to': 'Дуэли'},
        ]
    for rubric in rubrics:
        tag = Tag(name=rubric['ref'], title=rubric['title'])
        tag.save()
        rubric['tag'] = tag
        print("tag %s added" % tag.name)
    for post in Post.objects.all():
        for rubric in rubrics:
            if post.rubric == rubric['ref']:
                post.tags.add(rubric['tag'])
                post.save()
                rubric['tag'].post_count += 1
                print("post %d tag %s added" % (post.id, rubric['tag'].name))
    for rubric in rubrics:
        rubric['tag'].save()


def fix_user_tags():
    for post in Post.objects.all():
        for tag in post.tags.all():
            try:
                user_tag = UserTag.objects.get(title = tag.title, user = post.author)
                user_tag.post_count = Post.objects.filter(tags__id = tag.id, author = post.author).count()
            except UserTag.DoesNotExist:
                user_tag = UserTag(title = tag.title, user = post.author, post_count = 1)
            user_tag.save()
            print("post %d tag %s added" % (post.id, tag.title))
#    # Update changed tags post counts
#    for tag in fix_tags.keys():
#        if fix_tags[tag] is not None:
#            fix_tags[tag].post_count = Post.objects.filter(tags__id = fix_tags[tag].id).count()
#            fix_tags[tag].save()
#            try:
#                user_tag = UserTag.objects.get(title = fix_tags[tag].title, user = post.author)
#                user_tag.post_count = Post.objects.filter(tags__id = fix_tags[tag].id, author = post.author).count()
#            except UserTag.DoesNotExist:
#                user_tag = UserTag(title = fix_tags[tag].title, user = post.author, post_count = 1)
#            user_tag.save()

_depricated/blog/legacy/controllers/user.py
__author__ = 'dante'

from django.contrib import auth
from datetime import date
from waaagh.multiblog.tools.misc import get_random_key
from waaagh.multiblog.models import UserProfile, FilterTag, FilterUser, User, Tag

def block_user(user):
    user.is_active = False
    user.save()

def unblock_user(user):
    user.is_active = True
    user.save()

def get_user_settings(user):
    filters = {
        UserProfile.filter_all : 'all',
        UserProfile.filter_include : 'include',
        UserProfile.filter_exclude : 'exclude',
        }

    profile = user.get_profile()

    user_data = {
        'e_mail': user.email,
        'city': user.get_profile().city,
        'country' : user.get_profile().country,
        'about': user.get_profile().about,

        'blog_title': profile.blog_title,
        'blog_description': profile.blog_description,
        'new_messages_notify': profile.new_messages_notify,
        'new_bookmarked_comments_notify': profile.new_bookmarked_comments_notify,
        'new_my_post_comments_notify': profile.new_my_post_comments_notify,
        'always_keep_bookmarks': profile.always_keep_bookmarks,
        'keep_bookmarks': profile.keep_bookmarks,

        'filter_tags': filters[profile.filter_tags],
        'filter_tags_list': [ filter_tag.filtered_tag.title for filter_tag in user.filtertag_set.all() ],
        'filter_users': filters[profile.filter_users],
        'filter_users_list' : [ filter_user.filtered_user.username for filter_user in user.stream_owner.all() ],
    }
    if user.get_profile().birth_date is not None:
        user_data.update({
            'empty_birth': 'false',
            'birth_day' : user.get_profile().birth_date.day,
            'birth_month' : user.get_profile().birth_date.month,
            'birth_year' : user.get_profile().birth_date.year
        })
    else:
        user_data.update({ 'empty_birth': 'true', 'birth_day' : '', 'birth_month' : '', 'birth_year' : '' })
    return user_data

def update_user_secure(user, password, new_password, email):
    auth_user = auth.authenticate(username=user.username,
        password=password)
    if auth_user is None or not auth_user.is_active:
        return 'denied'
    user.email=email
    if new_password != '':
        user.set_password(new_password)
    user.save()
    return 'success'

def update_user_profile(user, country, city, date_value, about):
    profile = user.get_profile()
    profile.country = country
    profile.city = city
    profile.about = about
    if date_value:
        profile.birth_date = date(date_value['year'], date_value['month'], date_value['day'])
    else:
        profile.birth_date = None
    profile.save()
    return 'success'

def update_user_settings(user, blog_title, blog_desc, message_notify, bookmarked_notify, post_notify, keep):
    profile = user.get_profile()
    profile.blog_title = blog_title
    profile.blog_description = blog_desc
    profile.new_messages_notify = message_notify
    profile.new_bookmarked_comments_notify = bookmarked_notify
    profile.new_my_post_comments_notify = post_notify
    if keep is True:
        profile.always_keep_bookmarks = True
    else:
        profile.always_keep_bookmarks = False
        profile.keep_bookmarks = keep
    profile.save()
    return 'success'

def update_user_avatar(user, data):
    if not data['avatar']:
        return
    import os
    from waaagh.settings import AVATARS_DIR

    profile = user.get_profile()
    file_name, file_extension = os.path.splitext(data['avatar'].name)
    avatar = get_random_key() + file_extension
    with open(os.path.join(AVATARS_DIR, avatar), 'wb+') as destination:
        for chunk in data['avatar'].chunks():
            destination.write(chunk)
    try:
        os.remove(os.path.join(AVATARS_DIR, profile.avatar))
    except Exception:
        pass
    profile.avatar = avatar
    profile.save()

def update_stream(user, tag_filter, tags, user_filter, users):
    filters = {
        'all': UserProfile.filter_all,
        'include': UserProfile.filter_include,
        'exclude': UserProfile.filter_exclude,
        }

    profile = user.get_profile()
    profile.filter_users = filters[user_filter]
    profile.filter_tags = filters[tag_filter]

    failed_users = []
    users_obj = []
    if filters[user_filter] is not UserProfile.filter_all:
        for username in users:
            try:
                users_obj.append(User.objects.get(username = username))
            except User.DoesNotExist:
                failed_users.append(username)

    failed_tags = []
    tag_obj = []
    if filters[tag_filter] is not UserProfile.filter_all:
        for tag in tags:
            try:
                tag_obj.append(Tag.objects.get(title = tag))
            except Tag.DoesNotExist:
                failed_tags.append(tag)

    if len(failed_users) is not 0 or len(failed_tags) is not 0:
        return {'fail' : {'tags': failed_tags, 'users': failed_users }}

    FilterTag.objects.filter(stream_owner = user).delete()
    for tag in tag_obj:
        FilterTag(filtered_tag = tag, stream_owner = user).save()

    FilterUser.objects.filter(stream_owner = user).delete()
    for filtered_user  in users_obj:
        FilterUser(filtered_user = filtered_user, stream_owner = user).save()

    profile.save()
    return 'success'

_depricated/blog/legacy/tools/__init__.py
__author__ = 'dante'

_depricated/blog/views.py
from _depricated.blog import post_list

__author__ = 'dante'

from flask import Blueprint, render_template, jsonify, request, url_for
from flask.ext.login import current_user
import json

module = Blueprint('blog', __name__)


@module.route('/post/<post_id>')
def post(post_id):
    return render_template("../templates/blog/post.html", data=post_utils.get_single_post(post_id))


@module.route('/_update_post', methods=['POST'])
def update_post():
    if not current_user.is_authenticated():
        return jsonify(redirect=url_for('auth.signin_page'))
    return jsonify(result=post_utils.update_post(json.loads(request.form.get('data'))))

#
# @module.route('/_post_list_data', methods=['POST'])
# def post_list_data():
#     data = json.loads(request.form.get('data'))
#
#     def safe_get(key):
#         return data[key] if key in data.keys() else None
#
#     return jsonify(result=posts_list_data(safe_get('page'), safe_get('tag'), safe_get('user')))

@module.route('/')
@module.route('/<int:page>')
@module.route('/blog/<string:author>')
@module.route('/blog/<string:author>/<int:page>')
@module.route('/blog/<string:author>/tag/<string:tag>')
@module.route('/blog/<string:author>/tag/<string:tag>/<int:page>')
@module.route('/tag/<string:tag>')
@module.route('/tag/<string:tag>/<int:page>')
def main(page=0, author=None, tag=None):
    return render_template("blog/main.html", data=post_list(page=page, author=author, tag=tag))

_depricated/blog2/blog/__init__.py
__author__ = 'dromanow'

from .views import module

_depricated/blog2/blog/views.py
from .blog.tools import process_post, get_data, get_posts

__author__ = 'Denis Romanov'

from flask import Blueprint, render_template, jsonify, request, url_for
from flask.ext.login import current_user
import json

module = Blueprint('blog', __name__, url_prefix='/social')


@module.route('/_update_post', methods=['POST'])
def update_post():
    data = json.loads(request.form.get('data'))
    res = get_data(data)
    if res:
        return jsonify(res)
    if not current_user.is_authenticated():
        return jsonify(redirect=url_for('auth.signin_page'))
    return jsonify(process_post(data, current_user))


@module.route('/')
@module.route('/user/<user>')
@module.route('/tag/<tag>')
@module.route('/post/<post>')
def main(user=None, tag=None, post=None):
    return render_template(
        "blog/main.html",
        posts=get_posts(user=user, tag=tag, post=post),
        post=post, tag=tag, user=user
    )

_depricated/templates/blog/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bunker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/extern/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/extern/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
    </style>

    {% block styles %}{% endblock %}
    <script type="text/javascript" src="/static/extern/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/static/extern/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/extern/knockout-2.2.1.js"></script>
    {% block scripts %}{% endblock %}
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {#    <!-- Le fav and touch icons -->#}
    {#    <!--  <link rel="shortcut icon" href="../assets/ico/favicon.ico">#}
    {#    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">#}
    {#    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">#}
    {#    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png"> -->#}
</head>

<body>

<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            {% block logo %}
                <a class="brand" href="{{ url_for('blog.main') }}"><strong><span style="color: #db0000">B</span>unker <span style="color: #db0000">L</span>ogs</strong></a>
            {% endblock %}
            {% block navbar %}
            {% endblock %}
            {% block auth %}
            <ul class="nav pull-right">
                {% if current_user.is_authenticated() %}
                    <div class="btn-group">
                        <a href="{{ url_for('blog.main', author=current_user.name) }}" class="btn btn-inverse">{{ current_user.name }}</a>
                        <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li class="disabled"><a href="#">Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="{{ url_for('auth.signout_page') }}">Sign Out</a></li>
                        </ul>
                    </div>
                {% else %}
                    <li><a href="{{ url_for('auth.signin_page') }}">Sign In</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
    </div>
</div>

<div class="container">
{% block container %}
    <div class="row">
        <div class="span9">
            <div id="post_view">
            {%- if data.author %}
                <div class="page-header">
                    <h1>
                    {%- if data.author.blog.title -%}
                        {{ data.author.blog.title }}
                    {%- else -%}
                        Блог: {{ data.author.name }}
                    {%- endif %}
                        <a href="{{ url_for('blog.main', author=data.author.name) }}">&raquo;</a>
                        {%- if data.author.blog.description -%}
                        <br/>
                        <small class="muted">{{ data.author.blog.description }}</small>
                    {%- endif %}
                    </h1>
                </div>
            {% endif %}
            </div>
                {% block text_area %}
                    {% for post in data.posts %}
                        <h3><span class="muted">{% if post.rate %}{{ post.rate|rate }} - {% endif %}</span> <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a></h3>
                        <p>{{ post.text.text|markdown }} {% if post.text.read_more %}<a href="{{ url_for('blog.post', post_id=post.id) }}">Читать дальше &rarr;</a>{% endif %}</p>
                        <p>
                            {%- for tag in post.tags -%}
                                <a href="{{ url_for('blog.main', author=data.author.name if data.author else None, tag=tag) }}"><span class="label label-success">{{ tag }}</span></a>
                            {% endfor -%}
                        </p>
                        <div class="row-fluid">
                        {% if post.author.avatar %}
                            <img class="pull-left" src="http://dabunker.com/static/avatars/{{ post.author.avatar }}" style="max-height: 36px; margin-right: 10px">
                        {% endif %}
                        <span> <a href="{{ url_for('blog.main', author=post.author.name) }}">{{ post.author.name }}</a>
                            <span class="badge badge-warning">{{ post.author.rate|rate }}</span> <span class="muted"> <br> <small>{{ post.time|local_date }}</small></span> </span>
                        <a class="pull-right" href="{{ url_for('blog.post', post_id=post.id) }}">Комментарии: {{ post.comments }}{% if post.new_count %} (Новых: {{ post.new_count }}){% endif %}</a>
                        </div>
                        <hr/>
                    {% endfor %}
                    <div>
                        <ul class="pager">
                            {% if data.prev != None %}
                                <li class="previous">
                                    <a href="{{ url_for('blog.main', page=data.prev, author=data.author.name if data.author else None, tag=data.tag) }}">&larr; Предыдущие</a>
                                </li>
                            {% endif %}
                            {% if data.next != None %}
                                <li class="next">
                                    <a href="{{ url_for('blog.main', page=data.next, author=data.author.name if data.author else None, tag=data.tag) }}">Следующие &rarr;</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                {% endblock %}
            </div>

            <div class="span3">
{#                <a class="btn btn-danger" href="{{ url_for('builder.main') }}"><strong>Head Quoters</strong> <span class="icon-star icon-white"></span></a>#}
                <div style="text-align: center">
                    <a class="btn btn-large btn-danger" href="">
                        <h2>Head Quoters</h2>
                        <h6>Online Roster Builder</h6>
                    </a>
                </div>
{#                <a href="/blog/GreenskinBrothersStudio/"><img style="margin-bottom: 20px;" src="http://www.dabunker.com/static/avatars/164997062297525091984152.jpg"></a>#}
{#                <div class="well" style="text-align: center">#}
{#                    <h2><a href="/blog/GreenskinBrothersStudio/">GBS</a></h2>#}
{#                    Greenskin Brothers Studio's Blog#}
{#                </div>#}
{#                {% if stable.side_bar.bookmarks %}#}
{#                    <div class="well">#}
{#                        <p><h4><a href="/bookmarks">Закладки</a></h4></p>#}
{#                        {% for bookmark in stable.side_bar.bookmarks %}#}
{#                            <p><a href="/post/{{ bookmark.id }}">{{ bookmark.title }}</a> ({{ bookmark.comments }}{% if bookmark.new_comments %}, новых: {{ bookmark.new_comments }}{% endif %})</p>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                {% endif %}#}
                <div class="row-fluid">
                    <hr/>
                    <p><h4>Разделы</h4></p>
                    {% if data.author -%}
                        {%- for tag in data.tags -%}
                            <a href="{{ url_for('blog.main', tag=tag, author=data.author.name) }}"><span class="label label-success">{{ tag }}</span></a>
                        {% endfor -%}
                    {%- else -%}
                        {%- for tag in data.tags -%}
                            <a href="{{ url_for('blog.main', tag=tag) }}"><span class="label label-info">{{ tag }}</span></a>
                        {% endfor -%}
                    {%- endif -%}
                </div>
{#                <div class="well">#}
{#                    <p><h4>Популярные</h4></p>#}
{#                    {% for post in stable.side_bar.most_rated %}#}
{#                        <p>{% if post.rate > 0 %}+{% endif %}{{ post.rate }} <a#}
{#                                href="/post/{{ post.id }}">{{ post.title }}</a></p>#}
{#                    {% endfor %}#}
{#                </div>#}
{#                <div class="well">#}
{#                    <p><h4>Обсуждаемые</h4></p>#}
{#                    {% for post in stable.side_bar.most_commented %}#}
{#                        <p><a href="/post/{{ post.id }}">{{ post.title }}</a> ({{ post.comments }})</p>#}
{#                    {% endfor %}#}
{#                </div>#}
{#                <div class="well">#}
{#                    <p><h4>Онлайн</h4></p>#}
{#                    {% for online_user in stable.side_bar.online %}#}
{#                        <a href="/user/{{ online_user }}">{{ online_user }}</a>,#}
{#                    {% endfor %}#}
{#                </div>#}
            </div>
        </div>
    {% endblock %}
    <hr>
y    <footer>
        <p>&copy; <a href="mailto:kurvivor19@yandex.ru?subject=support">hq-builder.com</a></p>
    </footer>
</div>
<!-- /container -->
</body>
</html>